[workspace]
members = ["crate/tec-2", "crate/custom_macro"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"


[workspace.dependencies]
lalrpop-util = { version = "0.22.2", features = ["lexer", "unicode"] }
lazy_static = "1.5.0"
num_enum = "0.7.4"
hex = "0.4.3"


